"""добавлены поля угадываемого слова и кол-ва попыток

Revision ID: 2c49d9860626
Revises: 
Create Date: 2022-04-24 12:12:09.780601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c49d9860626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_word', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_try', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_column('users', 'current_try')
    op.drop_column('users', 'current_word')
    # ### end Alembic commands ###
